services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # SvelteKit Application Service (acts as front and back end)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    restart: always
    depends_on:
      - postgres
    ports:
      - '5173:5173'
    environment:
      # This URL is used by SvelteKit's server-side code to connect to the DB
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - .:/app # Mount local code for hot-reloading
      - /app/node_modules
    networks:
      - app-network

# Define networks and volumes
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
